// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  element: string
  date: string
  today: string
}
declare var cssExports: CssExports;
export = cssExports;
