// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string
  grid: string
  element: string
}
declare var cssExports: CssExports;
export = cssExports;
